title: Kelvin Chen
logo: /assets/img/Kelvin.jpg
description: This is a website for projects I've worked on.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
